In [1]:
# Numpy - Array
# Pandas - Data Frame
# Matplotlib - Graph

In [9]:
import numpy as np
np.array([10,20,30])
# print(array)

array([10, 20, 30])

In [1]:
try:
    import numpy
    print("NumPy is installed.")
except ImportError:
    print("NumPy is not installed.")


NumPy is installed.


In [245]:
import numpy as pn
arr=pn.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr)

print(arr[0,2])
print(arr[1,2])
#not working
# arr.append(30)
# print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
30
60


In [249]:
# if no data is available we can fill it with nan
arr=pn.array([1,2,np.nan])
print(arr)

[ 1.  2. nan]


In [6]:
import numpy as np
a=np.array([10,20,30,50,40] )
a[2:4]

array([30, 50])

In [7]:
print(a)
b=a[1:5]
b[1]= 696
print(b)
print(a)

[10 20 30 50 40]
[ 20 696  50  40]
[ 10  20 696  50  40]


In [10]:
# in numpy range is written as arange
a=np.arange(5)
b=np.arange(0,10)
c=np.arange(5,100,17)
print(a)
print(b)
print(c)

[0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]
[ 5 22 39 56 73 90]


In [27]:
a=np.arange(9)
print(a)
b=a.reshape (3,3)
print(b)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [34]:
x=np.arange(9)
print(x)
# y=x.reshape(3,3)
y=np.ones((3,3))
y=np.ones((6,9)) * 5
print(y)

[0 1 2 3 4 5 6 7 8]
[[5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5.]]


In [35]:
# 'F' means column major order
mat1=np.arange(30)
mat2=np.reshape(mat1,(6,5),'F')
print(mat2)

[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


In [39]:
# 'C' means row major order
mat1=np.arange(30)
mat2=np.reshape(mat1,(3,10),'C')
print(mat2)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [44]:
#  transverse in matrix 
print(mat2)
print(mat2.T)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
[[ 0 10 20]
 [ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]]


In [46]:
import numpy as np
a=np.arange(9)
b=a.reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [48]:
c=np.arange(8,17)
d=c.reshape(3,3)
print(d)

[[ 8  9 10]
 [11 12 13]
 [14 15 16]]


In [64]:
print(b+d)
print(b-d)
print((b-d) + 8)
print(b*d)
# print((b+d).T)
# print(e)
# print(e.T)

[[ 8 10 12]
 [14 16 18]
 [20 22 24]]
[[-8 -8 -8]
 [-8 -8 -8]
 [-8 -8 -8]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[  0   9  20]
 [ 33  48  65]
 [ 84 105 128]]


In [66]:
# for actual multiplication of matrix we'll use '@'
print(b@d)

[[ 39  42  45]
 [138 150 162]
 [237 258 279]]


In [68]:
a=np.arange(12)
b=a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
#  ravel is used to flatten the array
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [73]:
# for a graph plotting
a=np.linspace(20,40,7)
print(a)

[20.         23.33333333 26.66666667 30.         33.33333333 36.66666667
 40.        ]


In [77]:
#  QUARTERLY SALE OF A STATIONARY SHOP
Copy_Sale= [ 1200,3410,2400,1000]
Pen_Sale = [ 260,3400,1000,1300]
Book_Sale = [10000,35000,13000,10000]
sales= np.array([Copy_Sale,Pen_Sale,Book_Sale])
print(sales)

[[ 1200  3410  2400  1000]
 [  260  3400  1000  1300]
 [10000 35000 13000 10000]]


In [81]:
x=int(input("type 1 for copy sale,type 2 pen sale,type 3 for book sale:"))
y=int(input("Enter the quarter you want: "))
print("your required data is : ",sales[x-1][y-1])

type 1 for copy sale,type 2 pen sale,type 3 for book sale: 1
Enter the quarter you want:  3


your required data is :  2400


In [89]:
r={'Copy':0,'Pen':1,'Book':2}
q={'q1':0,'q2':1,'q3':2,'q4':3}
print(r['Copy'])
print(sales[r['Copy']][q['q2']])

0
3410


In [90]:
# Slicing 
a=np.arange(100)
print(a[0::6])

[ 0  6 12 18 24 30 36 42 48 54 60 66 72 78 84 90 96]


In [91]:
print(a[0:34:])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33]


In [93]:
arr1=np.arange(12)
arr2=arr1.reshape(3,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [97]:
y=arr2[1:3,1:3]
print(y)

[[ 5  6]
 [ 9 10]]
